### ISSUE TITLE
[Bug] [Code: ATWxL] No translation, only error

### ISSUE THREAD

**Issue by gaige** [FlineDev/ReMafoX#25]
## Steps to Reproduce:

1. Set up an existing Project (Obj-C and Swift)
1. Configured for RaMafoX with Azure translate
1. Selected an untranslated string
1. Pressed the key combination

## Expected Behavior:

Expected the translation to happen

## Current Behavior:

Received an error message:

No Strings(dict) file with the source language English was found.
Make sure your configured paths are correct or press 'Rescan Strings(dict) files'

Seems odd, but I've got the following strings files:
```
% find . -name \*.strings
./de.lproj/CartographicaMobile-InfoPlist.strings
./de.lproj/CartoMobileTests-InfoPlist.strings
./de.lproj/InfoPlist.strings
./Interface/de.lproj/Tasks.strings
./Interface/de.lproj/LinePolyEditPanel~ipad.strings
./Interface/de.lproj/LaunchScreenView.strings
./Interface/de.lproj/CloneViewController.strings
./Interface/de.lproj/Map.strings
./Interface/de.lproj/GenericLoginView.strings
./Interface/de.lproj/TaskDetailHeaderView.strings
./Interface/de.lproj/DownloadStatusViewController.strings
./Interface/de.lproj/ShpFileTypes.strings
./Interface/de.lproj/Localizable.strings
./Interface/de.lproj/AddressDetailView.strings
./Interface/de.lproj/LinePolyEditPanel.strings
./Interface/de.lproj/Configure.strings
./Interface/de.lproj/MainStoryboard.strings
./Interface/de.lproj/OverlayDetailView.strings
./Interface/de.lproj/TaskDetailView.strings
./Interface/de.lproj/FormFieldEditorView.strings
./Interface/de.lproj/Settings.strings
./Interface/en.lproj/ShpFileTypes.strings
./Interface/en.lproj/InfoPlist.strings
./Interface/es.lproj/Tasks.strings
./Interface/es.lproj/LinePolyEditPanel~ipad.strings
./Interface/es.lproj/LaunchScreenView.strings
./Interface/es.lproj/CloneViewController.strings
./Interface/es.lproj/Map.strings
./Interface/es.lproj/GenericLoginView.strings
./Interface/es.lproj/TaskDetailHeaderView.strings
./Interface/es.lproj/DownloadStatusViewController.strings
./Interface/es.lproj/ShpFileTypes.strings
./Interface/es.lproj/Localizable.strings
./Interface/es.lproj/AddressDetailView.strings
./Interface/es.lproj/LinePolyEditPanel.strings
./Interface/es.lproj/Configure.strings
./Interface/es.lproj/MainStoryboard.strings
./Interface/es.lproj/OverlayDetailView.strings
./Interface/es.lproj/TaskDetailView.strings
./Interface/es.lproj/FormFieldEditorView.strings
./Interface/es.lproj/Settings.strings
./Interface/fr.lproj/Tasks.strings
./Interface/fr.lproj/LinePolyEditPanel~ipad.strings
./Interface/fr.lproj/LaunchScreenView.strings
./Interface/fr.lproj/CloneViewController.strings
./Interface/fr.lproj/Map.strings
./Interface/fr.lproj/GenericLoginView.strings
./Interface/fr.lproj/TaskDetailHeaderView.strings
./Interface/fr.lproj/DownloadStatusViewController.strings
./Interface/fr.lproj/ShpFileTypes.strings
./Interface/fr.lproj/Localizable.strings
./Interface/fr.lproj/AddressDetailView.strings
./Interface/fr.lproj/LinePolyEditPanel.strings
./Interface/fr.lproj/Configure.strings
./Interface/fr.lproj/MainStoryboard.strings
./Interface/fr.lproj/OverlayDetailView.strings
./Interface/fr.lproj/TaskDetailView.strings
./Interface/fr.lproj/FormFieldEditorView.strings
./Interface/fr.lproj/Settings.strings
./es.lproj/CartographicaMobile-InfoPlist.strings
./es.lproj/CartoMobileTests-InfoPlist.strings
./es.lproj/InfoPlist.strings
./Settings.bundle/en.lproj/Root.strings
./ShpFileTypes.strings
./CartoMobileSnapshot/de.lproj/InfoPlist.strings
./CartoMobileSnapshot/es.lproj/InfoPlist.strings
./CartoMobileSnapshot/fr.lproj/InfoPlist.strings
./fr.lproj/CartographicaMobile-InfoPlist.strings
./fr.lproj/CartoMobileTests-InfoPlist.strings
./fr.lproj/InfoPlist.strings
./third-party/CTUtils/en.lproj/InfoPlist.strings
./third-party/CTUtils/CTUCrashTest/en.lproj/MainMenu.strings
./third-party/CTUtils/CTUCrashTest/en.lproj/InfoPlist.strings
./third-party/GDALFramework/en.lproj/Info-XercesPlist.strings
./third-party/GDALFramework/en.lproj/InfoPlist.strings
./third-party/GDALFramework/en.lproj/Proj4-InfoPlist.strings
./third-party/GDALFramework/libjpeg/libjpeg/en.lproj/InfoPlist.strings
./third-party/GDALFramework/libjpeg/libjpegTests/en.lproj/InfoPlist.strings
./third-party/GDALFramework/hdf/hdfTests/en.lproj/InfoPlist.strings
./third-party/GDALFramework/hdf/hdf/en.lproj/InfoPlist.strings
./third-party/GDALFramework/netcdf/libnetcdf/en.lproj/InfoPlist.strings
./third-party/GDALFramework/netcdf/libnetcdfTests/en.lproj/InfoPlist.strings
./third-party/ColorPicker/de.lproj/ColorPickerViewController.strings
./third-party/ColorPicker/es.lproj/ColorPickerViewController.strings
./third-party/ColorPicker/fr.lproj/ColorPickerViewController.strings
./third-party/ocmock-framework/Examples/iOS7Example/iOS7ExampleTests/en.lproj/InfoPlist.strings
./third-party/ocmock-framework/Examples/iOS7Example/iOS7Example/en.lproj/InfoPlist.strings
./third-party/ocmock-framework/Examples/iOS5Example/iOS5ExampleTests/en.lproj/InfoPlist.strings
./third-party/ocmock-framework/Examples/iOS5Example/iOS5Example/en.lproj/InfoPlist.strings
```

## Environment

ATWxL

<details>
<summary>Show environment details</summary>

- App Version: 1.0.2 (Build 51)
- System Version: 12.6 (Build 21G115)
- System CPU: Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz

</details>

**Comment by Jeehut** [comment]
@gaige Thank you for reporting this.

To help you or investigate a potential issue, I need more information from you:
1. What is the language you use while coding, providing the initial text in (= your development language)?
2. What language is set as the source language in the config file (see "General" pane)?
3. Which of all these Strings files would you expect the new key to be added to?
4. Can you find this Strings file in the dropdown menu on the dialog that appears after pressing the shortcut?

Please also note that the shortcut to open the dialog window to add a new translation does not immediately start the machine translation. For that to happen, you need to press the "Machine translate" button (or Cmd+M).

Please provide as much context as possible answering the above questions so I can help you.

**Comment by gaige** [comment]
1. Development language is English (en)
2. Source language is English (With the American flag)
3. I'd expect it to be added to ./Interface/en.lproj/Localizable.strings — which may be the problem, as that doesn't exist (previously I hand-coded the LocalizedStrings() file)
4. No, it wasn't there. Once I added it, it was. However, I seem to continue to get the error.

Quitting the ReMafoX app and restarting will still cause the aforementioned error, even if the en.Localizable.strings file exists. However, once I select the file from the drop-down it gives me the ability to add the translation key, etc. However, it doesn't carry over information from Xcode, and it doesn't allow me to click either Insert button.

Also, hitting Cancel will pop me back into Xcode, but it won't remove the window; so if I then try again, I will get a second window.

**Comment by gaige** [comment]
Also, closing the ReMafoX app with the error up will cause the error and translation panel to re-appear when re-launching.

If I _then_ cancel and quit again it won't come back when I quit and relaunch.

**Comment by gaige** [comment]
I seem to have somewhat better luck if I choose a string in one of the Swift files as opposed to Objective C. Although I still am getting the error about not being able to locate the file. I'm wondering if the non-base path is throwing it somehow?

**Comment by Jeehut** [comment]
@gaige Thank you for answering the questions and the detailed information.

You've run into multiple different problems here, mostly caused by the first issue, let me break things up a bit so we can tackle each problem separately:

## Error Code `ATWxL`

> I'd expect it to be added to ./Interface/en.lproj/Localizable.strings — which may be the problem, as that doesn't exist (previously I hand-coded the LocalizedStrings() file)

ReMafoX expects you to have a `.strings(dict)` file in your selected source language to exist. Otherwise it won't work properly and you will get an error all the time. If you want to use ReMafoX, please make sure you add a `Localizable.strings` file for the English language (in your case, as that's your source language). This is the main problem the code `ATWxL` points to. After adding a `Localizable.strings` file and selecting `Localizable.strings` in the dropdown, this error should disappear.

## Pre-selected Strings file
The logic for ReMafoX to pre-select a `.strings` file in the dropdown of the Add Translation menu is as follows:

1. First, it checks what project and Strings(dict) file you last pressed one of the `Insert` buttons with
1. If it finds such a project and Strings(dict) file, it checks if this project and file still exist
1. If there's no such project and Strings(dict) file, it will try to default to a file named `Localizable.strings`
1. If there's no Strings file named like this, it will simply default to the first Strings(dict) file it finds

This information might help you understand what's going on.

## Carrying information over from Xcode

> However, it doesn't carry over information from Xcode

When you quit the ReMafoX app and restart it again, as of now, the previously entered information in the Add Translation window gets lost and you'll be greeted with an empty window. If you expect something else here, feel free to create a dedicated feature request to solve this and I will consider implementing it in a future update.

The workaround to get the source translation back as of now would be to press `Cancel` and simply restart the whole process in Xcode with the shortcut (or menu entry). This will cause the Xcode Source Editor extension to pass along the source translation to the window.

## Disabled Insert Button

>  it doesn't allow me to click either Insert button

If you can see the "Insert" buttons but they are disabled, one of the following things can be the reason for this:

1. The `Translation Key` field is empty or contains only whitespace characters. Provide a key if that's the case.
2. No project was selected in the top-left `Project` dropdown. Select a project here.
3. No Strings file was selected in the top `Strigns file` dropdown. Select a Strings file here.
4. The translation for the source language (third text field in the window) is sempty. Provide a translation if that's the case.

If none of these things is the case for you, please take a screenshot of your window and report this as a separate error.

## Windows on Launch

> Also, closing the ReMafoX app with the error up will cause the error and translation panel to re-appear when re-launching.
> If I then cancel and quit again it won't come back when I quit and relaunch.

This seems to be some window management magic built-in to Mac apps (written in SwiftUI). I may be able to disable this behavior for the Add Translation window, but I'm not sure if this is a "better" user experience per se. If you think that the window shouldn't reopen (which causes the window to do its safety checks which leads to the error appearing again), then please let me know why so I can consider turning this magic behavior off somehow.

## Obj-C support

> I seem to have somewhat better luck if I choose a string in one of the Swift files as opposed to Objective C. Although I still am getting the error about not being able to locate the file. I'm wondering if the non-base path is throwing it somehow?

Where you trigger the Add Translation window from shouldn't really matter, your main issue clearly is the missing `en.lproj/Localizable.strings` file. Without it, things won't work properly.

Having that said, currently, ReMafoX is generating an `enum` file and as far as I know, most enum types are not supported in Objective-C and I have to admit I haven't tested ReMafoX with Objective-C code. This is clearly something I missed in version 1.0 of the app, but I just created https://github.com/FlineDev/ReMafoX/issues/26. Please upvote it so I can prioritize it higher and provide this feature soon.


Please let me know if the above information helps.

**Comment by gaige** [comment]
Thanks for the additional info.  Last night, as an experiment, I created a new en.lproj at the root level and move the Localizable.Strings files to the en, es, de, and fr at the root level. 

I was still getting the error, and I couldn't seem to get to the point where I could ever insert any items. Although I could set the file in the drop-down, after getting the error I couldn't insert in Xcode, and that seemed to prevent it from remembering the Localizable.strings file the next time I tried.

I'm purging the ReMafoX files now and restarting the project with an existing Localizable.Strings file to see if that helps.

**Comment by Jeehut** [comment]
@gaige Yeah, I think restarting the setup process after making sure you have an English version of your `Localizable.strings` file available could help resolve the issue. I hope this works!

If not, feel free to send me a ZIP file with the relevant parts in your projects where I can reproduce the issue. I'm happy to investigate and fix any issues either with the app or with your configuration to help you out. Send the file to support@fline.dev or simply temporarily invite me to the project on GitHub (if that's possible).

**Comment by gaige** [comment]
Unfortunately, purging the `ReMafoX.swift` and `CartoMobile.remafox` files and then re-opening the project in ReMafoX didn't seem to help much. It's still claiming it can't find the file correctly (and I've been testing solely with some Swift/SwiftUI files in the project).

I've also noticed, it seems to be searching files in directories that are listed in the exclusion paths. I can see this as well in the UI when I first set the skip path.  Preview Matching Files consistently includes items that are explicitly in paths that I've added to the list of Subpaths to skip in search.  The only way to ignore them seems to be to exclude the top level directories and manually include every individual directory I want to add.

This probably isn't a big issue for most projects, but in my case my two most significant projects have a lot of files (CartoMobile, the one I'm testing here, has 38000, most of which are cross-platform and not relevant for searching). For sake of comparison, my "big" project has 58000 files, most of which are cross-platform and not relevant for searching.

So, this time I:
1. Created the missing en.lproj/Localizable.strings file (with English = English strings to match the English = X strings in the preceding files)
2. Removed the ./ from the search path and added in appropriate sub-paths for the couple of directories I need searched at the top level
3. Regenerated the ReMafoX file

To give a bit more context, this project is already human-translated for prior versions, but as I'm moving more code to Swift and SwiftUI, I want to move to using enums instead of Strings—hence my interest in ReMafoX.

Even with those changes, though, every time I try to create a new string in Xcode (from a SwiftUI file), I get the above error and it selects the first .strings file (which is a Xib-related strings file, and which doesn't have a corresponding English version... because it's using the Base.lproj)

After that, I added the corresponding English files for every XIB. Clearing out the ReMafoX files at that point and starting the process over doesn't result in the error messages.

However, it also doesn't result in things working correctly. Specifically, the translation window comes up, it selects one of my Xib-related Strings files as the default. When I change from the Xib-related to the `Localizable.strings` file and enter the Translation Key, it never enables the Insert button

<img width="1052" alt="CleanShot 2022-10-15 at 05 16 01@2x" src="https://user-images.githubusercontent.com/3351751/195978931-4c2a002b-9de4-497e-9db6-b13de980dcc9.png">

Any thoughts?

**Comment by gaige** [comment]
As for sending along the files or inviting to github, my projects aren't on github, and as I mentioned, the projects are sizeable.

If there's a subset of information you need, I'm happy to crate that up (like the lproj directories, etc.), but I'm not sure access to source will be possible.

With that said, if you have some diagnostics you'd like me to run, I'm happy to give it a try. This looks promising, and I understand that our 10-year-old evolving product isn't representative of most indy developers. However, it's probably representative of a number of enterprise developers.

**Comment by Jeehut** [comment]
@gaige Thank you for the write-up and for being patient in getting this to work.

As I just released the app few days ago, I did expect some more bugs to be revealed once the app gets more real-world usage. I really want to tackle them within the next weeks, and you seem to describe multiple bugs here, which I really want to investigate and help fixing so everything works smoothly in your projects.

I see at least two things I want to investigate which I can't reproduce with any projects I've tested with, including larger Open Source projects such as [DuckDuckGo](https://github.com/duckduckgo/iOS/pull/1312), because I totally want to cover these as well, not only Indie projects (hence the Max tier).

I can totally understand that you might not want or be able to provide me with any real code. I think if you provided me with just the original structure of files and the Strings files (feel free to remove their contents if needed, the file structure is the important part here) and the full ReMafoX config file and steps to reproduce the issues with these files, I should be able to investigate and fix things.

The easiest way to provide me with only the structure of files but no actual contents, is to copy the contents of your project to a new folder, e.g. named `Issue25Demo` on your Desktop, open the Terminal and run this command:

```bash
find ~/Desktop/Issue25Demo | xargs truncate -s 0
```

Please be cautious about the path to provide here to the `find` as the contents of all files within that path will be removed. But this way, if you're fine with me seeing the names of your project files, you can also keep all files of the project and send them over to me. Just don't forget to copy over and override the `.remafox` file and any other files you _want_ me to see the contents of, such as some Strings files. Then you could ZIP that folder and upload it here or send it to support@fline.dev or create a private GitHub repo and invite me there, whichever way you prefer.

**Comment by gaige** [comment]
I've added the `./,` back to the path (and the `third-party/` to the subpaths to skip). In that configuration, it's still seeing the files in the subdirectories. If you remove the `./` from the Paths to search then these are skipped. (That's safe to do because the .strings files are all in the `Interface` subdirectory).

I'll send along a zip of the project, pruned down substantially, however I'm still seeing the symptoms.

**Comment by Jeehut** [comment]
@gaige Waiting for the email then. I'm really curious what's going on here...

**Comment by gaige** [comment]
I need to resend with a different mail server, for some reason your mail host has banned my mail server.  Not sure why… :shrug:-GaigeOn Oct 15, 2022, at 11:09, Cihat Gündüz ***@***.***> wrote:﻿
@gaige Waiting for the email then. I'm really curious what's going on here...

**Comment by Jeehut** [comment]
@gaige You can also reach me through Twitter if email still doesn't work (don't know what the problem is either):
https://twitter.com/Jeehut

You can also try commits@cihatguenduez.de if you want to try a different E-Mail, but I think it's the same server...

**Comment by gaige** [comment]
I uploaded the zip to Dropbox and sent you a link.-GaigeOn Oct 15, 2022, at 11:50, Cihat Gündüz ***@***.***> wrote:﻿
@gaige You can also reach me through Twitter if email still doesn't work (don't know what the problem is either):
https://twitter.com/Jeehut
You can also try ***@***.*** if you want to try a different E-Mail, but I think it's the same server...

**Comment by Jeehut** [comment]
@gaige Thank you, I have now successfully received the ZIP file and looked into the project to investigate.

Unfortunately, I can't reproduce the disabled "Insert" button issue. May I ask if you're on the Free/Pro/Max tier? Because you definitely need the Max tier for this size of project, but then you should see that the limits are exceeded like so:
![Screen Shot 2022-10-15 at 18 55 15](https://user-images.githubusercontent.com/6942160/195998810-bea6e997-5d4f-4069-b4fe-3360eb4c119a.png)

Once I upgraded to the Max tier, the Insert buttons worked for me though, so I can not reproduce the issue:
![Screen Shot 2022-10-15 at 18 56 55](https://user-images.githubusercontent.com/6942160/195998831-07963bc2-6145-496e-a9ec-92a2f32daaa7.png)

I think, I have required enough effort from you though. Next, I will investigate the logic for enabling/disabling the Insert button in code and try to discover any potential issues and maybe simply rework the code to be even more reliable. This really is a blocker for using ReMafoX and I will do what is needed to make it work.

As for the skip files issue, I will skip that for now to focus on the more important issue first.
Thank you for your patience. I will update you once I have discovered anything new.

**Comment by Jeehut** [comment]
Alright, I've already found a bug that might have caused some confusion while investigating this, even if it's not the root cause. I've reported it here and will fix it soon: https://github.com/FlineDev/ReMafoX/issues/42.

**Comment by Jeehut** [comment]
I played around with the settings a bit, adding a language here etc. and now I could finally reproduce the disabled button issue. I have to stop investigating now, but at least I have something to investigate now for tomorrow. Progress! 🎉

**Comment by gaige** [comment]
Thanks for the update.  I just got back to my computer.  Yes, using a max subscription. My other app is substantially larger with a lot more text…. If this works well enough, I may finally get some translations going on it. CartoMobile, as you can see already has translations, but not for new development I’ve been doing.-GaigeOn Oct 15, 2022, at 13:36, Cihat Gündüz ***@***.***> wrote:﻿
I played around with the settings a bit, adding a language here etc. and now I could finally reproduce the disabled button issue. I have to stop investigating now, but at least I have something to investigate now for tomorrow. Progress! 🎉

**Comment by Jeehut** [comment]
@gaige Alright, I'll keep you updated. I'm also interested in how the experience is with really large projects. I haven't done much performance testing with larger projects than 2,000 keys. If you have more, then I'm curious to see what parts might be a bit slow and need some work. But one step at a time...

**Comment by Jeehut** [comment]
@gaige I just found the root cause for the buttons being disabled and fixed it!

The problem was that I had incorrect logic for an early return when users are on the Max tier, where no limit checks are needed. The reason I couldn't reproduce the issue at first was that I was on the Pro plan in my test environment.

I will release an update with this fix very soon (`1.0.3`). I will also adjust the environment info to also include the current tier so in the future I can replicate that when trying to reproduce issues.

Thank you for your patience!

**Comment by Jeehut** [comment]
Just uploaded and submitted version `1.0.3` with the disabled button fix for review. Should be available in ~24 h from now.
